changelog:
  exclude:
    labels:
      - skip-changelog
    authors:
      - dependabot
      - renovate
      - renovate[bot]
  categories:
    - title: Breaking Changes
      labels:
        - breaking
    - title: New Features
      labels:
        - enhancement
        - feature
    - title: Bug Fixes
      labels:
        - bug
        - fix
    - title: Security
      labels:
        - security
    - title: Dependencies
      labels:
        - dependencies
        - rust
    - title: Other Changes
      labels:
        - "*"
