name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

defaults:
    run:
        shell: bash

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os:
                    - "ubuntu-22.04"
                    - "macos-10.15"
                    - "windows-2019"
                just_cmd:
                    - "test"
                    - "check"
                    - "fix"
                    - "build"
        steps:
            - uses: actions/checkout@v2
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
            - uses: Swatinem/rust-cache@v2
            - uses: extractions/setup-just@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - run: just ${{ matrix.just_cmd }}
