name: Winget
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The latest version (ex: 1.2.3)'
        required: true

jobs:
  publish-winget:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
        working-directory: ${{ github.workspace }}/package/winget
    env:
        GITHUB_TOKEN: ${{ secrets.WINGET_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: true
    - name: Create manifest and submit PR 📦
      run: |
        ./build.ps1 -Version "${{ github.event.inputs.version }}" -Token $env:GITHUB_TOKEN
